/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package info3bibliotecatp;
import javax.swing.*;
import java.util.List;
/**
 *
 * @author MSI
 */
public class ComentariosVentana extends javax.swing.JFrame {

    private int idLibro;
    private int idUsuario;
    private String tituloLibro;
    
    /**
     * Creates new form ComentariosVentana
     */
    public ComentariosVentana(int idLibro, int idUsuario, String tituloLibro) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.idLibro = idLibro;
        this.idUsuario = idUsuario;
        this.tituloLibro = tituloLibro;
        labelTituloLibro.setText("Comentarios sobre: " + tituloLibro);
        cargarComentarios();
        double promedio = GestionComentarios.obtenerPromedioPuntuacion(idLibro);
        jLabelPromedio.setText("Promedio de puntuación: " + String.format("%.2f", promedio));

    }

        private void cargarComentarios() {
        List<String> lista = GestionComentarios.obtenerComentariosPorLibro(idLibro);
        areaComentarios.setText("");
        for (String comentario : lista) {
            areaComentarios.append("- " + comentario + "\n");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTituloLibro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaComentarios = new javax.swing.JTextArea();
        campoComentario = new javax.swing.JTextField();
        botonComentar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();
        comboPuntuacion = new javax.swing.JComboBox<>();
        jButtonPuntuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTituloLibro.setText(" Lo opina la gente sobre: [titulo]");

        areaComentarios.setEditable(false);
        areaComentarios.setColumns(20);
        areaComentarios.setLineWrap(true);
        areaComentarios.setRows(5);
        areaComentarios.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaComentarios);

        campoComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoComentarioActionPerformed(evt);
            }
        });

        botonComentar.setText("Comentar");
        botonComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComentarActionPerformed(evt);
            }
        });

        jLabel1.setText("Agrega tu comentario:");

        jLabelPromedio.setText("Promedio de puntuacion: ");

        comboPuntuacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jButtonPuntuar.setText("Puntuar");
        jButtonPuntuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPuntuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTituloLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPuntuar)
                                    .addComponent(comboPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonComentar)
                                .addComponent(campoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelTituloLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPromedio)
                        .addGap(59, 59, 59)
                        .addComponent(comboPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButtonPuntuar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(botonComentar))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoComentarioActionPerformed

    private void botonComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComentarActionPerformed
        // TODO add your handling code here:
        String texto = campoComentario.getText().trim();
        if (!texto.isEmpty()){
            GestionComentarios.insertarComentario(idUsuario,idLibro,texto);
            campoComentario.setText("");
            cargarComentarios();
        }else{
            JOptionPane.showMessageDialog(this,"El comentario no puede estar vacio.");
        }
        
    }//GEN-LAST:event_botonComentarActionPerformed

    private void jButtonPuntuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPuntuarActionPerformed
        // TODO add your handling code here:
            int puntuacion = Integer.parseInt(comboPuntuacion.getSelectedItem().toString());
    GestionComentarios.insertarPuntuacion(idUsuario, idLibro, puntuacion);

    double promedio = GestionComentarios.obtenerPromedioPuntuacion(idLibro);
    jLabelPromedio.setText("Promedio de puntuación: " + String.format("%.2f", promedio));
    }//GEN-LAST:event_jButtonPuntuarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaComentarios;
    private javax.swing.JButton botonComentar;
    private javax.swing.JTextField campoComentario;
    private javax.swing.JComboBox<String> comboPuntuacion;
    private javax.swing.JButton jButtonPuntuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTituloLibro;
    // End of variables declaration//GEN-END:variables
}
